### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by carlos-fonseca-vr** [diofeher/bbb-v2#19]
[-] A Globo está pedindo uma proof of work gigante (6) pra esse usuário, tentando o próximo...
 Teve erro em XXXXXXXX@gmail.com.  Testando com outro usuário...

**Comment by rafadefine** [comment]
Isso é quando um usuário já votou várias vezes, aí a Globo deixa a página lerda para votar. 
Igual quando ocorre manualmente, que só fica carregando... carregando...
