### ISSUE TITLE
A Globo está pedindo uma proof of work gigante ({hashcashZeros}) pra esse usuário, tentando o próximo...

### ISSUE THREAD

**Issue by katherinefernandes** [diofeher/bbb-v2#28]
Olá, estava usando o bot, até que comecou a aparecer essa mensagem. O que isso quer dizer e como resolver o problema? Valeu

**Comment by diofeher** [comment]
Isso quer dizer que vc já votou / ou errou muitos captchas, tem que esperar um pouco pra votar de novo ou votar com outra conta. @katherinefernandes
