### ISSUE TITLE
Senhas que são alteradas do nada

### ISSUE THREAD

**Issue by fmarchesotti** [diofeher/bbb-v2#5]
Após deixar o Bot rodando por alguns minutos, eu recebi um aviso no e-mail dizendo que houve uma tentativa de redefinição da senha do e-mail que eu usei na conta globo, e a senha da própria conta globo foi alterada de um IP dos Emirados Árabes Unidos.
Resolvi fazer um teste com outra conta e também aconteceu tal intrusão.
Por mais que a conta que eu estava usando era uma conta vazia, é no mínimo estranho ter essa invasão provocada dessa forma. Muito cuidado com o uso da senha nesses bots, pois potencialmente existe alguma coisa nessa linha de comando que permite que isso aconteça

**Comment by diofeher** [comment]
Cara, o código tá livre aí pra ser auditado, não tem nada de malicioso nele. Não faço idéia do pq vc recebeu esse e-mail, mas não vi mais ninguém recebendo esse alerta. Você só instalou esse único bot? Pq o código tá livre pra ser olhado aí, n tem nada de malicioso.
